CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS measurements;
DROP TABLE IF EXISTS clients;

CREATE TABLE IF NOT EXISTS employees (
	eid			integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name	varchar(16) NOT NULL CONSTRAINT valid_first_name CHECK (first_name <> ''),
	last_name	varchar(16) NOT NULL CONSTRAINT valid_last_name CHECK (last_name <> ''),
	username	varchar(16) NOT NULL,
	password_hash varchar(100)
);

CREATE TABLE IF NOT EXISTS clients (
	cid			integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	first_name	varchar(16) NOT NULL CONSTRAINT valid_first_name CHECK (first_name <> ''),
	last_name	varchar(16) NOT NULL CONSTRAINT valid_last_name CHECK (last_name <> ''),
	age			integer NOT NULL CONSTRAINT positive_age CHECK (age BETWEEN 1 AND 120),
	height_cm 	integer NOT NULL CHECK (height_cm BETWEEN 30 AND 300),
	weight_kg 	integer NOT NULL CHECK (weight_kg BETWEEN 1 AND 500)
);

CREATE TABLE IF NOT EXISTS measurements (
	mid			integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	cid			integer references clients(cid),
	measuredAt	TIMESTAMP NOT NULL
);

